### ISSUE TITLE
use with degrees / radians

### ISSUE THREAD

**Issue by stephanschulz** [dzlonline/ofxBiquadFilter#3]
I have been using this great add-on for a while. 

I'm now wondering how i can be extend to also smooth degree readings I am getting for tracking a rotating object.
A continues rotation jumps from 0 to 360 degrees and currently confuses the 1 dimensional filter.
Would you have any tips?

Thanks a lot.

**Comment by dzlonline** [comment]
Hi.
The actual filter (s) does not care what runs through it. Whatever jumps
between 0 and 360 degrees happens before it is fed to the filters. Some
method needs to be inserted that will "wrap" the values so that the angle
values keep rising/falling for a given rotation. After filtering you can
"un wrap" so only
0 to 360 occurs if your application are depending on it.
Let me know if this makes sense...

Regards
Dzl

On Jan 10, 2018 19:19, "Stephan Schulz" <notifications@github.com> wrote:

I have been using this great add-on for a while.

I'm now wondering how i can be extend to also smooth degree readings I am
getting for tracking a rotating object.
A continues rotation jumps from 0 to 360 degrees and currently confuses the
1 dimensional filter.
Would you have any tips?

Thanks a lot.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dzlonline/ofxBiquadFilter/issues/3>, or mute the thread

**Comment by stephanschulz** [comment]
you are right I have to feed it a slowly changing value with out the wraparound jump.

even just converting to radians will not help since it jumps from 1 to -1.

anyway thanks for your quick reply. I will keep on scratching my brain.

**Comment by HalfdanJ** [comment]
I actually added a function for this usecase called `updateDegree` that tries to solve the issue you mention.

**Comment by stephanschulz** [comment]
interesting.
does this mean it would take degrees as input or still would need a values that keeps rising/falling?
also what does the circleSize be?

**Comment by HalfdanJ** [comment]
It takes degrees as input, and I think circleSize should be 360 in that case (or TWO_PI if its radians). Havent used this function in a very long time, so might be wrong :)
